import Pic1 from './assets/pic1.jpg'
import Pic2 from './assets/pic2.jpg'
import Pic3 from './assets/pic3.jpg'
import Pic4 from './assets/pic4.jpg'
import Pic5 from './assets/pic5.jpg'
import Pic6 from './assets/pic6.jpg'
import Pic7 from './assets/pic7.jpg'
import Pic8 from './assets/pic8.jpg'
import Pic9 from './assets/pic9.jpg'



const events1 = [{title:"Event 1", body:"This is the first event for this slide"}, {title:"Event 2", body:"This is the first event for this slide"}]


const slide1= {name:"image1",image:Pic1, events:[], description:"Un volcán (Del portugués volcão, y este del latín Vulcānus 'Vulcano', dios romano del fuego.) es una estructura geológica generalmente una montaña por la que emerge el magma que se divide en lava y gases provenientes del interior de la Tierra. ​El ascenso del magma ocurre en episodios de actividad violenta denominados erupciones, que pueden variar en intensidad, duración y frecuencia, desde suaves corrientes de lava hasta explosiones extremadamente destructivas." }
const slide2= {name:"image2",image:Pic2, events:[], description:"Un astro, en particular el Sol, está en el ocaso cuando, por efecto de la rotación de la Tierra, atraviesa el plano del horizonte y pasa del hemisferio visible al no visible. Es decir, cuando su altura es cero, pasando de positiva a negativa. En el caso del Sol, ello determina el fin del día. El antónimo de ocaso es amanecer, también llamado orto. El ocaso es llamado también atardecer o anochecer."}
const slide3= {name:"image3",image:Pic3, events:[], description:"A river is a natural flowing watercourse, usually a freshwater stream, flowing on the Earth's land surface or inside caves towards another waterbody at a lower elevation, such as an ocean, sea, bay, lake, wetland, or another river. In some cases, a river flows into the ground or becomes dry at the end of its course without reaching another body of water. Small rivers can be referred to by names such as creek, brook, and rivulet. There are no official definitions for these various generic terms for a watercourse as applied to geographic features,[1] although in some countries or communities, a stream is customarily referred to by one of these names as determined by its size. Many names for small rivers are specific to geographic location; examples are run in some parts of the United States, burn in Scotland and Northeast England, and beck in Northern England. Sometimes a river is defined as being larger than a creek,[2] but not always; in English the language is vague compared to some languages like French, where a fleuve flows into the sea and a rivière is a tributary of another rivière or fleuve"}
const slide4= {name:"image4",image:Pic4, events:[], events:events1, description:"In geology, rock (or stone) is any naturally occurring solid mass or aggregate of minerals or mineraloid matter. It is categorized by the minerals included, its chemical composition, and the way in which it is formed. Rocks form the Earth's outer solid layer, the crust, and most of its interior, except for the liquid outer core and pockets of magma in the asthenosphere. The study of rocks involves multiple subdisciplines of geology, including petrology and mineralogy. It may be limited to rocks found on Earth, or it may include planetary geology that studies the rocks of other celestial objects."}
const slide6= {name:"image6",image:Pic6, events:[], description:"A lake is an often naturally occurring, relatively large and fixed body of water on the Earth's surface. It is localized in a basin or interconnected basins surrounded by dry land.[1] Lakes lie completely on land and are separate from the ocean, although they may be connected with the ocean by rivers, such as Lake Ontario. Most lakes are freshwater and account for almost all the world's surface freshwater, but some are salt lakes with salinities even higher than that of seawater. Lakes vary significantly in surface area and volume of water."}
const slide5= {name:"image5",image:Pic5, events:[], description:"Best friends Becky and Hunter are climbing a mountain with Becky's husband Dan, who loses his footing and falls to his death. A year later, Becky has given up climbing and becomes an alcoholic recluse and contemplates suicide. She has estranged herself from her father, James, because he disapproved of her relationship with Dan. Just before the anniversary of Dan's death, Hunter invites Becky to climb the decommissioned 2,000-foot (610 m) B-67 TV Tower in the desert before it is demolished the following winter. Hunter tells Becky that she can scatter Dan's ashes from the top as a form of healing. A fearful Becky initially refuses before accepting, hoping to finally move on from Dan's death."}
const slide7= {name:"image7",image:Pic7, events:[], description:"A cottage, during England's feudal period, was the holding by a cottager (known as a cotter or bordar) of a small house with enough garden to feed a family and in return for the cottage, the cottager had to provide some form of service to the manorial lord.[1] However, in time cottage just became the general term for a small house. In modern usage, a cottage is usually a modest, often cosy dwelling, typically in a rural or semi-rural location and not necessarily in England. The cottage orné, often quite large and grand residences built by the nobility, dates back to a movement of rustic stylised cottages of the late 18th and early 19th century during the Romantic movemen"}
const slide8= {name:"image8",image:Pic8, events:[], description:"An island or isle is a piece of subcontinental land completely surrounded by water. Very small islands such as emergent land features on atolls can be called islets, skerries, cays or keys. An island in a river or a lake island may be called an eyot or ait, and a small island off the coast may be called a holm. Sedimentary islands in the Ganges Delta are called chars. A grouping of geographically or geologically related islands, such as the Philippines, is referred to as an archipelago."}
const slide9= {name:"image9",image:Pic9, events:[], description:"A hill is a landform that extends above the surrounding terrain. It often has a distinct summit, and is usually applied to peaks which are above elevation compared to the relative landmass, though not as prominent as mountains."}

const project1 = {name: "project1", slides: [slide1, slide2, slide3], description:"From the grand skyscrapers of sprawling cities to your favorite social media apps, project managers lead all types of projects across various industries. They use their project management expertise to execute and complete projects that bring brilliant ideas into reality.Project managers equip their teams with the tools to succeed and evole through projects. And they use various project management skills to do so, including:" }
const project2 = {name: "project2", slides: [slide4, slide5, slide6] , description:"A product manager (PM) is a professional role that is responsible for the development of products for an organization, known as the practice of product management. Product managers own the product strategy behind a product (physical or digital), specify its functional requirements, and manage feature releases. Product managers coordinate work done by many other functions (like software engineers, data scientists, and product designers), and are ultimately responsible for product outcomes"}
const project3 = {name: "project3", slides: [slide7, slide8, slide9], description: "The program manager has oversight of the purpose and status of the projects in a program and can use this oversight to support project-level activity to ensure the program goals are met by providing a decision-making capacity that cannot be achieved at project level or by providing the project manager with a program perspective when required, or as a sounding board for ideas and approaches to solving project issues that have program impacts. The program manager may be well-placed to provide this insight by actively seeking out such information from the project managers, although in large and/or complex projects, a specific role may be required. However this insight arises, the program manager needs this in order to be comfortable that the overall program goals are achievable." }

export const data = [project1, project2, project3]

export const overview = "For the Internet domain, see .website. For the on-demand archiving service, see WebCite. The usap.gov websiteA website (also written as a web site) is a collection of web pages and related content that is identified by a common domain name and published on at least one web server. Websites are typically dedicated to a particular topic or purpose, such as news, education, commerce, entertainment, or social media. Hyperlinking between web pages guides the navigation of the site, which often starts with a home page. The most-visited sites are Google, YouTube, and Facebook.All publicly-accessible websites collectively constitute the World Wide Web. There are also private websites that can only be accessed on a private network, such as a company's internal website for its employees. Users can access websites on a range of devices, including desktops, laptops, tablets, and smartphones. The app used on these devices is called a web browser."